# DO NOT change urls or headers, only headers value and body parameters' values

# Admin
@atkn=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YmYyZjA4OTQ5OTc5YTlmNzc0ZmQ0MCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzY3OTA4NiwiZXhwIjoxNzQzNzY1NDg2fQ.k2TI_jfPkq9it-MvmeUDYiW38_maqvZqgSTApfQ2nQA

# User1
@u1tkn=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGVlM2NlODAwNzBlMjdjYzk2NjM5MSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ3NDczNjEwLCJleHAiOjE3NDc1NjAwMTB9.q6dRsNWbaIH_FgmR-wZl50k40p6a0OGiTXXlo1O4m4A
@u1id=67dee3ce80070e27cc966391

# User2
@u2tkn=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGVlMzRhODAwNzBlMjdjYzk2NjM4YyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQzNjc5MTA0LCJleHAiOjE3NDM3NjU1MDR9.0j_vCPEdYmC4t0JH32cEv3EPIiUJvFuvdpoGcOL9Pxo
@u2id=67dee34a80070e27cc96638c

# Machine (token staticly generated)
@mtkn=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGRjNjliZjkzZmIxOTE0ODI4NTRiOSIsInJvbGUiOiJtYWNoaW5lIn0.ao5jQmK0cTLAcYcVcTdVl_cxT3KBRQStFq49dDxuoQs
@mid=674dc41cf93fb191482854ad

###

# Authentication
# it's necessary to call this endpoints in order to obtain the required token for accessing protected endpoints
# Admin
POST http://localhost:3000/api/v1/adminAuth
content-type: application/json

{
    "email":"admin@bluecycle.com",
    "password":"securepassword"
}
###
# User1
POST http://localhost:3000/api/v1/userAuth
content-type: application/json

{
    "email":"mariorossi@example.com",
    "password":"noooitsbahamuth"
}
###
# User2
POST http://localhost:3000/api/v1/userAuth
content-type: application/json

{
    "email":"toniobianchi@example.com",
    "password":"itsbahamut"
}

###

# Password reset
POST http://localhost:3000/api/v1/forgotPassword
content-type: application/json

{
    "email":"mariorossi@example.com"
}

###

# Post new user
POST http://localhost:3000/api/v1/users
content-type: application/json

{
    "email":"mariorossi@example.com",
    "name":"Mario Rossi"
}

###

# Get users
# < filters: id,email,code >
# Admin
GET http://localhost:3000/api/v1/users
Authorization: Bearer {{atkn}}
###
# Machine
GET http://localhost:3000/api/v1/users?code=6788810009
Authorization: Bearer {{mtkn}}

###

# Get user by id
# Admin
GET http://localhost:3000/api/v1/users/{{u2id}}
Authorization: Bearer {{atkn}}
###
# User1
GET http://localhost:3000/api/v1/users/{{u1id}}
Authorization: Bearer {{u1tkn}}
###
# User2
GET http://localhost:3000/api/v1/users/{{u1id}}
Authorization: Bearer {{u2tkn}}

###

# Patch user password
# Admin
PATCH http://localhost:3000/api/v1/users/{{u1id}}
content-type: application/json
Authorization: Bearer {{u1tkn}}

{
    "oldPassword":"nooitsbahamuth",
    "newPassword":"noooitsbahamuth"
}
###
# User1
PATCH http://localhost:3000/api/v1/users/{{u1id}}
content-type: application/json
Authorization: Bearer {{u1tkn}}

{
    "oldPassword":"noooitsbahamuth",
    "newPassword":"nnaak5hm"
}
###
# User2
PATCH http://localhost:3000/api/v1/users/{{u2id}}
content-type: application/json
Authorization: Bearer {{u2tkn}}

{
    "oldPassword":"itsbahamut",
    "newPassword":"w7t8twtge6"
}

###

# da qui
# ------------------------------------------------------------------------------------------------

# Get user coupons
# < filters: used,expired >
# User1
GET http://localhost:3000/api/v1/users/{{u1id}}/coupons?used=false&expired=false
Authorization: Bearer {{u1tkn}}
###
# User2
GET http://localhost:3000/api/v1/users/{{u2id}}/coupons?expired=false
Authorization: Bearer {{u2tkn}}

###

# Post new user coupon
# User1
POST http://localhost:3000/api/v1/users/{{u1id}}/coupons
content-type: application/json
Authorization: Bearer {{u1tkn}}

{
    "couponPrototype":"/api/v1/couponPrototypes/67bf6cf07bb68f5200f9d1e5"
}
###
# User2
POST http://localhost:3000/api/v1/users/{{u2id}}/coupons
content-type: application/json
Authorization: Bearer {{u2tkn}}

{
    "couponPrototype":"/api/v1/couponPrototypes/67bf6cc77bb68f5200f9d1e1"
}

###

# FUNZIONA

# Post new wishlisted coupon(prototypes)
# User1
POST http://localhost:3000/api/v1/users/{{u1id}}/wishlistedCoupons
content-type: application/json
Authorization: Bearer {{u1tkn}}

{
    "couponPrototype":"/api/v1/couponPrototypes/67bf6cc77bb68f5200f9d1e1"
}
###
# User2
POST http://localhost:3000/api/v1/users/{{u2id}}/wishlistedCoupons
content-type: application/json
Authorization: Bearer {{u2tkn}}

{
    "couponPrototype":"/api/v1/couponPrototypes/67bf6cc77bb68f5200f9d1e1"
}

###

# FUNZIONA

# Get user's wishlisted coupon prototypes
# User1
GET http://localhost:3000/api/v1/users/{{u1id}}/wishlistedCoupons
Authorization: Bearer {{u1tkn}}
###
# User2
GET http://localhost:3000/api/v1/users/{{u2id}}/wishlistedCoupons
Authorization: Bearer {{u2tkn}}

###

# FUNZIONA

# Get user's wishlisted coupon by id
# User 1
GET http://localhost:3000/api/v1/users/{{u1id}}/wishlistedCoupons/67e14bb9bfb608deeb9bc61c
Authorization: Bearer {{u1tkn}}
###
# User 2
GET http://localhost:3000/api/v1/users/{{u2id}}/wishlistedCoupons/675956b45e757f064f60db62
Authorization: Bearer {{u2tkn}}

###

# FUNZIONA

# Delete wishlisted coupon by id
# User1
DELETE http://localhost:3000/api/v1/users/{{u1id}}/wishlistedCoupons/67e14bb9bfb608deeb9bc61c
Authorization: Bearer {{u1tkn}}
###
# User2
DELETE http://localhost:3000/api/v1/users/{{u2id}}/wishlistedCoupons/675956b45e757f064f60db62
Authorization: Bearer {{u2tkn}}

# ------------------------------------------------------------------------------------------------

###

# Get coupon prototypes
# Admin
GET http://localhost:3000/api/v1/couponPrototypes
Authorization: Bearer {{atkn}}
###
# User1
GET http://localhost:3000/api/v1/couponPrototypes
Authorization: Bearer {{u1tkn}}
###
# User2
GET http://localhost:3000/api/v1/couponPrototypes
Authorization: Bearer {{u2tkn}}

###

# Get coupon prototype by id
# Admin
GET http://localhost:3000/api/v1/couponPrototypes/67bf6cc77bb68f5200f9d1e1
Authorization: Bearer {{atkn}}
###
# User1
GET http://localhost:3000/api/v1/couponPrototypes/67bf6cdc7bb68f5200f9d1e3
Authorization: Bearer {{u1tkn}}
###
# User2
GET http://localhost:3000/api/v1/couponPrototypes/67bf6cf07bb68f5200f9d1e5
Authorization: Bearer {{u2tkn}}

###

# Post new coupon prototype
# Admin
POST http://localhost:3000/api/v1/couponPrototypes
Authorization: Bearer {{atkn}}
content-type: application/json

{
    "store": "Ottica Trento",
    "discount": 20,
    "price": 25,
    "description": "Sconto del 20% su montature per occhiali"
}

###

# Delete coupon prototype
# Admin
DELETE http://localhost:3000/api/v1/couponPrototypes/67bf6dcc7bb68f5200f9d1fb
Authorization: Bearer {{atkn}}

###

# Get user's transactions
# Admin
GET http://localhost:3000/api/v1/users/{{u2id}}/transactions
Authorization: Bearer {{atkn}}
###
# User1
GET http://localhost:3000/api/v1/users/{{u1id}}/transactions
Authorization: Bearer {{u1tkn}}
###
# User2
GET http://localhost:3000/api/v1/users/{{u2id}}/transactions
Authorization: Bearer {{u2tkn}}

###

# Get user transactions collected
# < filters: date >
# Admin
GET http://localhost:3000/api/v1/users/{{u1id}}/transactions/collected
Authorization: Bearer {{atkn}}
###
# User1
GET http://localhost:3000/api/v1/users/{{u1id}}/transactions/collected?date=1747474030
Authorization: Bearer {{u1tkn}}
###
# User2
GET http://localhost:3000/api/v1/users/{{u2id}}/transactions/collected
Authorization: Bearer {{u2tkn}}

###

# Get machines
# < filters: available,proximity >
# Admin
# CAMBIARE COORDINATE(METTERE QUELLE DI POVO???)
GET http://localhost:3000/api/v1/machines?proximity[range]=1&proximity[from][latitude]=46.0387255&proximity[from][longitude]=11.147175500000001
Authorization: Bearer {{atkn}}
###
# User1
GET http://localhost:3000/api/v1/machines?
Authorization: Bearer {{u1tkn}}
###
# User2
GET http://localhost:3000/api/v1/machines?available=true
Authorization: Bearer {{u2tkn}}

###

# Get machine by id
# Admin
GET http://localhost:3000/api/v1/machines/674dc41cf93fb191482854ad
Authorization: Bearer {{atkn}}
###
# User1
GET http://localhost:3000/api/v1/machines/674dc660f93fb191482854b6
Authorization: Bearer {{u1tkn}}
###
# User2
GET http://localhost:3000/api/v1/machines/{{mid}}
Authorization: Bearer {{u2tkn}}

###

# Post new machine
# Admin
POST http://localhost:3000/api/v1/machines
Authorization: Bearer {{atkn}}
content-type: application/json

{
    "position": {
        "latitude":46.036299,
        "longitude":11.146156
    },
    "description":"6th_machine",
    "available":true
}

###

# Patch machine(change availability status)
# Admin
PATCH http://localhost:3000/api/v1/machines/{{mid}}
Authorization: Bearer {{atkn}}
content-type: application/json

{
    "available":true
}

###

# Get machine transactions
# Admin
GET http://localhost:3000/api/v1/machines/{{mid}}/transactions
Authorization: Bearer {{atkn}}

###

# Get machine transactions collected
# Admin
GET http://localhost:3000/api/v1/machines/{{mid}}/transactions/collected
Authorization: Bearer {{atkn}}

###

# Post new transaction
# Machine
POST http://localhost:3000/api/v1/transactions
Authorization: Bearer {{mtkn}}
content-type: application/json

{
    "user":"/api/v1/users/{{u1id}}",
    "machine":"/api/v1/machines/{{mid}}",
    "collected":10
}

###